package edu.student.itson.bda.ticketwizard.presentacion;

import edu.student.itson.bda.ticketwizard.control.ControlAgregarSaldo;
import java.math.BigDecimal;

public class AgregarSaldo extends javax.swing.JFrame {

    private final ControlAgregarSaldo control;

    public AgregarSaldo(ControlAgregarSaldo control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cantidadSaldo = new javax.swing.JTextField();
        confirmarSaldo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Cantidad a agregar:");

        jLabel1.setText("Indique la cantidad de saldo a agregar a su cuenta");

        cantidadSaldo.setText("...");
        cantidadSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadSaldoActionPerformed(evt);
            }
        });

        confirmarSaldo.setText("Confirmar");
        confirmarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarSaldoMouseClicked(evt);
            }
        });
        confirmarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 95, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cantidadSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmarSaldo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cantidadSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(confirmarSaldo)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarSaldoActionPerformed

    private void cantidadSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadSaldoActionPerformed

    private void confirmarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarSaldoMouseClicked
        BigDecimal saldoPorAgregar = new BigDecimal(this.cantidadSaldo.getText());
        this.control.agregarSaldo(saldoPorAgregar);
        this.control.mostrarFormularioInicioPerfil();
    }//GEN-LAST:event_confirmarSaldoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadSaldo;
    private javax.swing.JButton confirmarSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
