package edu.student.itson.bda.ticketwizard.presentacion;

import edu.student.itson.bda.ticketwizard.control.ControlEventos;
import edu.student.itson.bda.ticketwizard.entidades.Evento;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class EventosDisponibles extends javax.swing.JFrame {

    /**
     * Creates new form EventosDisponibles
     */
    private final ControlEventos control;
    private JComboBox<String> combo;

    public EventosDisponibles(ControlEventos control) {
        initComponents();
        this.control = control;
        this.llenarTablaEventos();
        this.llenarFiltroEventosEstados();
    }

    private void llenarFiltroEventosEstados() {
        String isAgain = "";
        combo = new JComboBox<String>();
        List<Evento> listaEventos = this.control.consultarListaEventos();
        for (Evento evento : listaEventos) {
            if (!evento.getEstado().equals(isAgain)) {
                combo.addItem(evento.getEstado());
                isAgain = evento.getEstado();
            }
        }
        this.comboBoxEstado.setModel(combo.getModel());
    }

    private void llenarFiltroEventosCiudades() {
        String isAgain = "";
        combo = new JComboBox<String>();
        List<Evento> listaEventos = this.control.consultarListaEventos();
        for (Evento evento : listaEventos) {
            if (!isAgain.equals(evento.getCiudad())) {
                if (this.comboBoxEstado.getSelectedItem().equals(evento.getEstado())) {
                    combo.addItem(evento.getCiudad());
                    isAgain = evento.getCiudad();
                }
            }
        }
        this.comboBoxCiudad.setModel(combo.getModel());
    }

    private void llenarFiltroEventosFecha() {
        List<Evento> listaEventos = this.control.consultarListaEventos();
        for (Evento evento : listaEventos) {
            if (this.comboBoxFecha.getSelectedItem().equals("Esta semana")) {

            } else if (this.comboBoxFecha.equals("Esta mes")) {

            } else if (this.comboBoxFecha.equals("Este año")) {

            }
        }
        this.comboBoxEstado.setModel(combo.getModel());
    }

    private void llenarTablaEventos() {
        List<Evento> listaEventos = this.control.consultarListaEventos();
        //sacamos el modelo de la tabla para poder manipular sus datos
        DefaultTableModel modelo = (DefaultTableModel) this.tlbEventos.getModel();
        // por cada artista devuelto por la clase ocntrol, lo agregamos a la JTable
        for (Evento evento : listaEventos) {
            Object[] filTabla = {
                evento.getNombre(),
                evento.getFecha(),
                evento.getEstado(),
                evento.getCiudad(),
                evento.getRecinto(),
                evento.getDescripcion(),};
            modelo.addRow(filTabla);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        pnlTablaEventos = new javax.swing.JScrollPane();
        tlbEventos = new javax.swing.JTable();
        comboBoxEstado = new javax.swing.JComboBox<>();
        comboBoxEstado = new javax.swing.JComboBox<>();
        comboBoxFecha = new javax.swing.JComboBox<>();
        comboBoxCiudad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");

        tlbEventos.setAutoCreateRowSorter(true);
        tlbEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nombre", "Fecha", "Estado", "Ciudad", "Recinto", "Descripcion"
            }
        ));
        pnlTablaEventos.setViewportView(tlbEventos);

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado" }));
        comboBoxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxEstadoItemStateChanged(evt);
            }
        });
        comboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEstadoActionPerformed(evt);
            }
        });

        comboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Esta semana", "Este mes", "Este año" }));
        comboBoxFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFechaActionPerformed(evt);
            }
        });

        comboBoxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciudad" }));
        comboBoxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(comboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(comboBoxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnBuscar)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTablaEventos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablaEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxFechaActionPerformed

    private void comboBoxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCiudadActionPerformed

    private void comboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEstadoActionPerformed

    private void comboBoxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxEstadoItemStateChanged
        this.llenarFiltroEventosCiudades();
    }//GEN-LAST:event_comboBoxEstadoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comboBoxCiudad;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JComboBox<String> comboBoxFecha;
    private javax.swing.JScrollPane pnlTablaEventos;
    private javax.swing.JTable tlbEventos;
    // End of variables declaration//GEN-END:variables
}
