package edu.student.itson.bda.ticketwizard.presentacion;

import edu.student.itson.bda.ticketwizard.control.ControlBoletos;
import edu.student.itson.bda.ticketwizard.control.ControlEventos;
import edu.student.itson.bda.ticketwizard.control.ControlUsuarios;
import edu.student.itson.bda.ticketwizard.entidades.Usuario;
import edu.student.itson.bda.ticketwizard.persistencia.BoletosDAO;
import edu.student.itson.bda.ticketwizard.persistencia.EventosDAO;

public final class InicioPerfil extends javax.swing.JFrame {

    private final ControlUsuarios control;

    public InicioPerfil(ControlUsuarios control) {
        this.control = control;
        initComponents();
        establecerInformacionUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarSaldo = new javax.swing.JButton();
        nombrePerfil = new javax.swing.JLabel();
        nombrePerfil1 = new javax.swing.JLabel();
        nombrePerfil3 = new javax.swing.JLabel();
        saldoPerfil = new javax.swing.JLabel();
        nombrePerfil5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEventos = new javax.swing.JMenu();
        menuBoletos = new javax.swing.JMenu();
        menuMiCuenta = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarSaldo.setText("Agregar saldo");
        agregarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarSaldoMouseClicked(evt);
            }
        });
        agregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSaldoActionPerformed(evt);
            }
        });

        nombrePerfil.setText("Bienvenido!!");

        nombrePerfil1.setText("Bienvenido!!");

        nombrePerfil3.setText("Saldo:");

        saldoPerfil.setText("Bienvenido!!");

        nombrePerfil5.setText("Nombre:");

        jButton1.setText("Comprar boletos");

        jButton2.setText("Ver boletos disponibles");

        jButton3.setText("Mis transacciones");

        menuEventos.setText("Eventos");
        menuEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEventosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuEventos);

        menuBoletos.setText("Mis boletos");
        menuBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBoletosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBoletos);

        menuMiCuenta.setText("Mi cuenta");
        menuMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMiCuentaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuMiCuenta);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrePerfil5)
                    .addComponent(nombrePerfil3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoPerfil)
                    .addComponent(nombrePerfil1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombrePerfil)
                        .addGap(61, 61, 61)
                        .addComponent(agregarSaldo)))
                .addGap(188, 188, 188))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jButton1)
                    .addGap(46, 46, 46)
                    .addComponent(jButton2)
                    .addGap(52, 52, 52)
                    .addComponent(jButton3)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(nombrePerfil1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePerfil5)
                    .addComponent(nombrePerfil)
                    .addComponent(agregarSaldo))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePerfil3)
                    .addComponent(saldoPerfil))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSaldoActionPerformed

    }//GEN-LAST:event_agregarSaldoActionPerformed

    private void agregarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarSaldoMouseClicked
        control.mostrarFormularioAgregarSaldo();
    }//GEN-LAST:event_agregarSaldoMouseClicked

    private void menuEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEventosMouseClicked
        EventosDAO eventosDAO = new EventosDAO();
        ControlEventos controlEventos = new ControlEventos(eventosDAO,this.control);
        this.dispose();
        controlEventos.iniciarCasoUso();
    }//GEN-LAST:event_menuEventosMouseClicked

    private void menuBoletosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBoletosMouseClicked
        BoletosDAO boletosDAO = new BoletosDAO();   
        Usuario usuario = control.consultarUsuario();
        ControlBoletos controlBoletos = new ControlBoletos(boletosDAO, usuario);
        this.dispose();
        controlBoletos.iniciarCasoUso();
    }//GEN-LAST:event_menuBoletosMouseClicked

    private void menuMiCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMiCuentaMouseClicked
        control.mostrarFormularioMiCuenta();
    }//GEN-LAST:event_menuMiCuentaMouseClicked

    public void establecerInformacionUsuario() {
        Usuario usuario = control.consultarUsuario();
        String nombreCompleto = usuario.getNombre() + " " + usuario.getApellido();
        this.nombrePerfil.setText(nombreCompleto);
        this.saldoPerfil.setText(String.valueOf(usuario.getSaldo()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuBoletos;
    private javax.swing.JMenu menuEventos;
    private javax.swing.JMenu menuMiCuenta;
    private javax.swing.JLabel nombrePerfil;
    private javax.swing.JLabel nombrePerfil1;
    private javax.swing.JLabel nombrePerfil3;
    private javax.swing.JLabel nombrePerfil5;
    private javax.swing.JLabel saldoPerfil;
    // End of variables declaration//GEN-END:variables
}
