package edu.student.itson.bda.ticketwizard.presentacion;

import edu.student.itson.bda.ticketwizard.control.ControlAgregarSaldo;
import edu.student.itson.bda.ticketwizard.entidades.Usuario;

public class InicioPerfil extends javax.swing.JFrame {

    private final ControlAgregarSaldo control;

    public InicioPerfil(ControlAgregarSaldo control) {
        this.control = control;
        initComponents();
        establecerInformacionUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarSaldo = new javax.swing.JButton();
        nombrePerfil = new javax.swing.JLabel();
        nombrePerfil1 = new javax.swing.JLabel();
        nombrePerfil3 = new javax.swing.JLabel();
        saldoPerfil = new javax.swing.JLabel();
        nombrePerfil5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarSaldo.setText("Agregar saldo");
        agregarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarSaldoMouseClicked(evt);
            }
        });
        agregarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSaldoActionPerformed(evt);
            }
        });

        nombrePerfil.setText("Bienvenido!!");

        nombrePerfil1.setText("Bienvenido!!");

        nombrePerfil3.setText("Saldo:");

        saldoPerfil.setText("Bienvenido!!");

        nombrePerfil5.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrePerfil5)
                    .addComponent(nombrePerfil3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoPerfil)
                    .addComponent(nombrePerfil1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombrePerfil)
                        .addGap(61, 61, 61)
                        .addComponent(agregarSaldo)))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(nombrePerfil1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePerfil5)
                    .addComponent(nombrePerfil)
                    .addComponent(agregarSaldo))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePerfil3)
                    .addComponent(saldoPerfil))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSaldoActionPerformed

    }//GEN-LAST:event_agregarSaldoActionPerformed

    private void agregarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarSaldoMouseClicked
        control.mostrarFormularioAgregarSaldo();
    }//GEN-LAST:event_agregarSaldoMouseClicked

    public void establecerInformacionUsuario() {
        Usuario usuario = control.consultarUsuario();
        String nombreCompleto = usuario.getNombre() + " " + usuario.getApellido();
        this.nombrePerfil.setText(nombreCompleto);
        this.saldoPerfil.setText(String.valueOf(usuario.getSaldo()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarSaldo;
    private javax.swing.JLabel nombrePerfil;
    private javax.swing.JLabel nombrePerfil1;
    private javax.swing.JLabel nombrePerfil3;
    private javax.swing.JLabel nombrePerfil5;
    private javax.swing.JLabel saldoPerfil;
    // End of variables declaration//GEN-END:variables
}
